# Generated by Django 4.1.4 on 2023-01-04 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crmapplication', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contract',
            old_name='Sales_contact',
            new_name='sales_contact',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='Support_contact',
            new_name='support_contact',
        ),
    ]
